# dex-amm vertical.
query AinizePools($skip: Int!, $first: Int!, $block: Block_height) {
  liquidityPools(first: $first, skip: $skip, orderBy: totalValueLockedUSD, orderDirection: desc, block: $block) {
    id
    name
    symbol
    isSingleSided
    totalValueLockedUSD
    inputTokens { id name symbol decimals lastPriceUSD }
    outputToken { id name symbol decimals }
    fees { feeType feePercentage }
    protocol { id name slug network type schemaVersion }
  }
  _meta(block: $block) { block { number timestamp } deployment hasIndexingErrors }
}
