/**
 * Regenerate `pipeline/sources.json` — the deployment set the benchmark pulls from.
 *
 * The ids are NOT typed in by hand. They are read from Messari's own deployment registry on GitHub
 * (`deployment/deployment.json`), which is public and needs no credential, so "which subgraph is this?" is
 * answerable by anyone without trusting us. Each entry keeps the protocol, the vertical (which decides
 * which standardized query text applies), and the registry status.
 *
 *   node pipeline/sources.mjs            # rewrite sources.json from the live registry
 *   node pipeline/sources.mjs --check    # exit 1 if the committed file disagrees with the registry
 *
 * The vertical -> query mapping IS the composability claim: one query text per vertical across every
 * protocol in it, plus identity.graphql which is byte-identical across all three.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REGISTRY = 'https://raw.githubusercontent.com/messari/subgraphs/master/deployment/deployment.json';

/** Messari's `schema` key -> the query text in pipeline/queries/ that its entities answer. */
const VERTICALS = { 'yield-aggregator': 'vaults', lending: 'markets', 'dex-amm': 'pools' };

/** CANDIDATES per vertical, not the final set. This file only knows what the registry says; whether a
 *  deployment is actually alive is a live fact, so `pull.mjs` health-checks every candidate and drops the
 *  unreachable and the badly-lagging ones with a recorded reason. Over-selecting here is what keeps enough
 *  protocols standing after that filter — measured 2026-09-04: of 12 candidates, 1 had no allocations, 1 had
 *  no available indexer, and 3 were stuck millions of blocks back with `hasIndexingErrors`. */
const PER_VERTICAL = { 'yield-aggregator': 8, lending: 8, 'dex-amm': 8 };

const NETWORK = 'ethereum';

export async function fromRegistry() {
  const r = await fetch(REGISTRY, { signal: AbortSignal.timeout(60_000) });
  if (!r.ok) throw new Error(`Messari registry unreachable: ${r.status}`);
  const reg = await r.json();
  const rows = [];
  for (const [protocol, p] of Object.entries(reg)) {
    const vertical = VERTICALS[p.schema];
    if (!vertical) continue;
    for (const [name, dep] of Object.entries(p.deployments ?? {})) {
      if (dep.network !== NETWORK) continue;
      if (dep.status !== 'prod') continue;
      const id = dep.services?.['decentralized-network']?.['query-id'];
      // Base58 subgraph id. A slug-shaped value means the protocol is hosted-service only and unusable here.
      if (!id || !/^[A-HJ-NP-Za-km-z1-9]{40,60}$/.test(id)) continue;
      rows.push({ deployment_id: id, protocol, deployment: name, schema: p.schema, query: vertical, network: NETWORK, status: dep.status });
    }
  }
  const picked = [];
  for (const schema of Object.keys(VERTICALS)) {
    // One deployment per PROTOCOL FAMILY, then alphabetical. Without the family rule the alphabetical
    // slice fills the lending vertical with five near-identical Aave forks (aave-amm, aave-arc, aave-rwa,
    // aave-v2, aave-v3), several of them long deprecated — which would make "one query across many
    // protocols" true only in the most literal sense. The rule is mechanical and declared here; it is not
    // a hand-pick of the deployments that happened to answer well.
    const family = (name) => name.split('-')[0];
    const seen = new Set();
    const group = rows
      .filter((x) => x.schema === schema)
      .sort((a, b) => a.deployment.localeCompare(b.deployment))
      .filter((x) => { const f = family(x.protocol); if (seen.has(f)) return false; seen.add(f); return true; });
    picked.push(...group.slice(0, PER_VERTICAL[schema] ?? 4));
  }
  return {
    _comment: 'Generated by pipeline/sources.mjs from Messari deployment/deployment.json (public, no credential). Do not hand-edit; re-run the script.',
    registry: REGISTRY,
    generated_at: new Date().toISOString(),
    network: NETWORK,
    identity_query: 'identity.graphql',
    _identity_note: 'identity.graphql is byte-identical across every entry below regardless of vertical — verified offline by research/tools/validate-query.mjs against schema-yield, schema-lending and schema-dex-amm.',
    sources: picked,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = path.join(HERE, 'sources.json');
  const next = await fromRegistry();
  if (process.argv.includes('--check')) {
    const cur = JSON.parse(fs.readFileSync(out, 'utf8'));
    const same = JSON.stringify(cur.sources) === JSON.stringify(next.sources);
    console.log(same ? 'sources.json matches the registry' : 'sources.json DIFFERS from the registry — re-run without --check');
    process.exit(same ? 0 : 1);
  }
  fs.writeFileSync(out, JSON.stringify(next, null, 2) + '\n');
  console.log(`sources.json: ${next.sources.length} deployments`);
  for (const s of next.sources) console.log(`  ${s.query.padEnd(8)} ${s.protocol.padEnd(22)} ${s.deployment_id}`);
}
